version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    volumes:
      - .:/app
      - ${DOWNLOAD_DIRECTORY}:${DOWNLOAD_URL}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: sh -c "python main.py"
    stdin_open: true
    tty: true
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: celery
    volumes:
      - .:/app
      - ${DOWNLOAD_DIRECTORY}:${DOWNLOAD_URL}
    depends_on:
      - fastapi
      - redis
    env_file:
      - .env
    command: sh -c "celery -A app.tasks worker -l info"
    stdin_open: true
    tty: true
    restart: always

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: always

